"""The OBJ machines, in the order tools/make_models.py writes them."""

from . import (
    assembler_1,
    big_pole,
    boiler,
    burner_mining_drill,
    electric_mining_drill,
    iron_chest,
    lab,
    lamp,
    offshore_pump,
    power_switch,
    pump,
    schematic_crate,
    small_pole,
    splitter,
    steam_engine,
    stone_cutter,
    stone_cutting_table,
    stone_furnace,
    storage_tank,
    wood_gasifier,
    wooden_chest,
)

MACHINES = {
    "stone_furnace": stone_furnace.build,
    "burner_mining_drill": burner_mining_drill.build,
    "wooden_chest": wooden_chest.build,
    "iron_chest": iron_chest.build,
    "electric_mining_drill": electric_mining_drill.build,
    "small_pole": small_pole.build,
    "big_pole": big_pole.build,
    "boiler": boiler.build,
    "steam_engine": steam_engine.build,
    "offshore_pump": offshore_pump.build,
    "assembler_1": assembler_1.build,
    "splitter": splitter.build,
    "lamp": lamp.build,
    "power_switch": power_switch.build,
    "schematic_crate": schematic_crate.build,
    "wood_gasifier": wood_gasifier.build,
    "storage_tank": storage_tank.build,
    "pump": pump.build,
    "lab": lab.build,
    "stone_cutting_table": stone_cutting_table.build,
    "stone_cutter": stone_cutter.build,
}
